### ISSUE TITLE
Wrong handling of binary data

### ISSUE THREAD

**Issue by Binozo** [electricbolt/dart-propertylistserialization#4]
Hi 👋

First of all thanks for this project!

Recently I encountered a bug regarding reading binary `<data>` from a binary plist.

You can test it yourself by looking into my pr #3 

Reproducing the Bug:

1. Checkout the test from #3 
2. Add the following code after line `83` in `binarypropertylistreader_test.dart`: 

`print("DATA 20 => " + String.fromCharCodes((dict["data20"] as ByteData).buffer.asUint8List()));`

3. Now run the test
4. You'll see the following output:

```
DATA 20 => bplist00Ú	
Vdata20VdoubleSintUfalseUutf16TdateTtrueUfloatUdata5UasciiO 	
#@      o  T h e   c o w   j u m p e d   o v e r   t h e   d o g3Áéü:ðà  	"?À  E _The cow jumped over the do$+/5;@EKQWnwyz»ÄÅÊÐ                            î
```

It seems like instead of reading the data bytes requested we get the full binary plist again

**Comment by electricbolt** [comment]
Thanks. I'll take a look at the PR and the issue over the weekend.

**Comment by electricbolt** [comment]
Hi Binozo,

Your use of ByteData conversion to a Uint8List is incorrect, and is a common gotcha. I've made the same mistake myself many times. The ByteData you get from the Map in your example is actually a smaller view of another larger ByteData (for performance purposes). Ensure you use the offsetInBytes and lengthInBytes as follows and it'll work just fine:

```
final data20 = dict["data20"] as ByteData;
print("DATA 20 => " + String.fromCharCodes(data20.buffer.asUint8List(data20.offsetInBytes, data20.lengthInBytes)));

```

I'll decline your PR, and add a similar test to ensure your specific binary use case works, and bump up the xml version.

Cheers!

**Comment by Binozo** [comment]
Oh thanks for the hint😅
